# unused
name: Create production builds

# on:
#   push:
#     branches: ['main']

jobs:
  android_production_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production
  ios_production_build:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
