# unused
name: Publish preview update

# on:
#   pull_request_labeled:
#     labels:
#       - Preview

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
