name: Release, Build, Publish (Continous Delivery)

permissions:
  contents: write

on:
  # workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    name: Build the app using eas-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: lts/*

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8.2.1
        with:
          packager: npm
          eas-version: latest
          token: ${{secrets.EXPO_APP}}

      - name: Install dependencies
        run: npm ci

      - name: Build on EAS
        # only android for now
        run: eas build --platform android --non-interactive

  # TODO:
  # publish:
  #   name: Build the app using eas-cli
  #   runs-on: ubuntu-latest
  #   steps:
